version: '3'

services:
  db-pgsql:
    container_name: pg-local
    image: postgres
    env_file:
      - ".env"
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
